name: Life_Bond_1.16
version: ${project.version}
main: me.jonatanc05.lifebond.Main
api-version: 1.13
authors: [Jonatanc05]
description: Bonds the life of players... for ever

commands:
  criar:
    description: cria um novo vínculo
  entrar:
    description: entra em um vínculo existente
  vinculos:
    description: lista os vínculos existentes
  meuvinculo:
    description: exibe vinculo do player
  sair:
    description: retira o player de seu vínculo atual